load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "ExampleSubsystem",
    srcs = ["ExampleSubsystem.kt"],
    visibility = ["//visibility:public"],
    deps = [
        "@bazelrio//libraries/java/wpilib/new_commands",
        #"@bazelrio//libraries/java/wpilib/wpilibj",
    ],
)
