load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "DriveSignal",
    srcs = ["DriveSignal.kt"],
    visibility = ["//visibility:public"],
    deps = [
    ],
)